import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF5F8',
  },
  safeArea: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  header: {
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: '#000',
    fontFamily: 'Raleway',
    marginBottom: 6,
  },
  location: {
    fontSize: 13,
    fontWeight: '400',
    color: '#000',
    fontFamily: 'Raleway',
  },
  searchContainer: {
    marginBottom: 24,
  },
  searchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 10,
    paddingLeft: 12,
    paddingRight: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 13,
    color: '#000',
    fontFamily: 'Raleway',
    paddingVertical: 0,
  },
  listContainer: {
    gap: 16,
  },
  cardContainer: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    flexDirection: 'row',
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  imageWrapper: {
    width: 98,
    height: 124,
    borderRadius: 8,
    overflow: 'hidden',
    marginRight: 12,
    backgroundColor: '#EC4899',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  cardContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  cardHeader: {
    marginBottom: 4,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  name: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    fontFamily: 'Raleway',
  },
  onlineIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#41D72D',
    marginLeft: 6,
  },
  services: {
    fontSize: 12,
    fontWeight: '300',
    color: '#000',
    fontFamily: 'Raleway',
  },
  badgesRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
  },
  badgeText: {
    fontSize: 8,
    fontWeight: '600',
    color: '#000',
    fontFamily: 'Raleway',
  },
  priceIcon: {
    fontSize: 8,
    color: '#000',
    fontWeight: '600',
  },
  detailsRow: {
    flexDirection: 'row',
    gap: 24,
    marginBottom: 10,
  },
  detailBlock: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 8,
    fontWeight: '600',
    color: '#000',
    fontFamily: 'Raleway',
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 8,
    fontWeight: '400',
    color: '#000',
    fontFamily: 'Raleway',
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    position: 'absolute',
    top: 12,
    right: 12,
  },
  actionButton: {
    width: 32,
    height: 32,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bookButton: {
    backgroundColor: '#EC4899',
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginTop: 8,
    alignItems: 'center',
  },
  bookButtonText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFF',
    fontFamily: 'Raleway',
  },
});